services:
  backend:
    image: webvirtbackend:dev
    hostname: backend
    ports:
      - 8000:8000
      - 127.0.0.1:5678:5678
    volumes:
      - .:/app
    command: ["sh", "-c", "python3 -m pip install debugpy && python3 -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      PYTHONOPTIMIZE: 1
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.develop
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - mariadb
